/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119304-gdb0e4eb845-20250420"
#endif /* AVUTIL_FFVERSION_H */
